$ErrorActionPreference = "Stop"

function Require-File {
    param(
        [Parameter(Mandatory = $true)][string]$Path,
        [Parameter(Mandatory = $true)][string]$Label
    )

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        throw "$Label is missing: $Path"
    }
}

function Invoke-Native {
    param(
        [Parameter(Mandatory = $true)][string]$Exe,
        [Parameter(Mandatory = $true)][string[]]$Args
    )

    & $Exe @Args
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) {
        throw "command failed (exit=$exitCode): $Exe $($Args -join ' ')"
    }
}

try {
    $scriptHome = Split-Path -Parent $MyInvocation.MyCommand.Path
    $root = if (Test-Path -LiteralPath (Join-Path $scriptHome "leo.exe") -PathType Leaf) {
        $scriptHome
    }
    else {
        Split-Path -Parent $scriptHome
    }
    $leoExe = Join-Path $root "leo.exe"
    $cupolaExe = Join-Path $root "tools\cupola\cupola-cli.exe"
    $aegisExe = Join-Path $root "tools\aegis\aegis.exe"
    $epiExe = Join-Path $root "tools\epi\epi-cli.exe"

    $intakePath = Join-Path $root "data\intake.json"
    $fallbackIntake = Join-Path $root "tools\aegis\data\intake.json"

    Require-File -Path $leoExe -Label "leo.exe"
    Require-File -Path $cupolaExe -Label "cupola-cli.exe"
    Require-File -Path $aegisExe -Label "aegis.exe"
    Require-File -Path $epiExe -Label "epi-cli.exe"

    if (-not (Test-Path -LiteralPath $intakePath -PathType Leaf)) {
        if (-not (Test-Path -LiteralPath $fallbackIntake -PathType Leaf)) {
            throw "intake.json is missing: $intakePath"
        }
        New-Item -ItemType Directory -Path (Split-Path -Parent $intakePath) -Force | Out-Null
        Copy-Item -LiteralPath $fallbackIntake -Destination $intakePath -Force
    }
    Require-File -Path $intakePath -Label "data\\intake.json"

    $stamp = Get-Date -Format "yyyyMMdd-HHmmss"
    $outDir = Join-Path $root ("out\self-audit-" + $stamp)
    $vaultDir = Join-Path $outDir "_vault"

    New-Item -ItemType Directory -Path (Join-Path $vaultDir "notes") -Force | Out-Null
    New-Item -ItemType Directory -Path (Join-Path $vaultDir "evidence") -Force | Out-Null

    Set-Content -LiteralPath (Join-Path $vaultDir "README.md") -Value @"
# Synthetic Vault

This vault is generated by RUN_SELF_AUDIT.ps1 for portable validation.
"@

    Set-Content -LiteralPath (Join-Path $vaultDir "notes\summary.txt") -Value @"
control: MFA enabled for privileged users
control: quarterly access review completed
"@

    Set-Content -LiteralPath (Join-Path $vaultDir "evidence\controls.json") -Value @"
{
  "controls": [
    {
      "id": "AC-01",
      "status": "implemented",
      "owner": "security"
    },
    {
      "id": "AC-02",
      "status": "monitoring",
      "owner": "platform"
    }
  ]
}
"@

    Write-Host "Running doctor..."
    Invoke-Native -Exe $leoExe -Args @(
        "doctor",
        "--cupola-bin", $cupolaExe,
        "--aegis-bin", $aegisExe,
        "--epi-bin", $epiExe
    )

    Write-Host "Running self-audit pipeline..."
    Invoke-Native -Exe $leoExe -Args @(
        "run",
        "--vault", $vaultDir,
        "--intake", $intakePath,
        "--out", $outDir,
        "--cupola-bin", $cupolaExe,
        "--aegis-bin", $aegisExe,
        "--epi-bin", $epiExe
    )

    $verifyPath = Join-Path $outDir "verify.json"
    $packZip = Join-Path $outDir "pack.zip"
    Require-File -Path $verifyPath -Label "verify.json"
    Require-File -Path $packZip -Label "pack.zip"

    $decisionPackPdf = Get-ChildItem -LiteralPath $outDir -Recurse -Filter "DecisionPack.pdf" |
        Select-Object -First 1
    $decisionPackHtml = Get-ChildItem -LiteralPath $outDir -Recurse -Filter "DecisionPack.html" |
        Select-Object -First 1
    $decisionPackManifest = Get-ChildItem -LiteralPath $outDir -Recurse -Filter "DecisionPack.manifest.json" |
        Select-Object -First 1
    $decisionPackSeal = Get-ChildItem -LiteralPath $outDir -Recurse -Filter "DecisionPack.seal.json" |
        Select-Object -First 1

    if ($null -eq $decisionPackPdf) { throw "DecisionPack.pdf is missing in $outDir" }
    if ($null -eq $decisionPackHtml) { throw "DecisionPack.html is missing in $outDir" }
    if ($null -eq $decisionPackManifest) { throw "DecisionPack.manifest.json is missing in $outDir" }
    if ($null -eq $decisionPackSeal) { throw "DecisionPack.seal.json is missing in $outDir" }

    $pdfSize = (Get-Item -LiteralPath $decisionPackPdf.FullName).Length
    if ($pdfSize -lt 50000) {
        throw "DecisionPack.pdf is too small: $pdfSize bytes (expected >= 50000)"
    }

    $verify = Get-Content -Raw -LiteralPath $verifyPath | ConvertFrom-Json
    if (-not $verify.ok) {
        throw "verify.json reports ok=false: $verifyPath"
    }

    Write-Host ""
    Write-Host "Self-audit complete."
    Write-Host "DecisionPack.html: $($decisionPackHtml.FullName)"
    Write-Host "DecisionPack.pdf:  $($decisionPackPdf.FullName) ($pdfSize bytes)"
    Write-Host "verify.json:       $verifyPath"
    Write-Host "pack.zip:          $packZip"
}
catch {
    Write-Error $_
    exit 1
}
